### ISSUE TITLE
Add newsletter subscription email input box

### ISSUE THREAD

**Issue by sd33m** [factn/resilience-landing-page#108]
**Page:** index.html

**Description:** a box, with a success or failure message

[Mockup]()

**Screenshot:**

**Comment by jwu910** [comment]
Can we fix the issue description? Page should be a semantic page or route like "home" or `/stories`.

The mockup link is incorrect and there is a lack of detail around what the scope of work is. Based on the content of the title, I would also remove the layout label.

**Comment by DAHuerta** [comment]
I am trying to find what this issue is addressing, then I will fix it.

**Comment by jwu910** [comment]
Thanks, i wasn't aware email subscriptions were set up or if there was a newsletter yet
