### ISSUE TITLE
[Layout] Recap of what the Resilience is offering

### ISSUE THREAD

**Issue by DAHuerta** [factn/resilience-landing-page#117]
Once the user is directed to the Get Resilience form, there will be a quick recap of all the ways that Resilience would be beneficial to organizations at the top of the page.

**Description:**
On the left side with will be a sales pitch - Left Aligned
A link to display how our users use the application - Left Aligned
The right side will be a checklist of features stored in a box - Center Aligned

[Mockup](https://www.figma.com/file/GLg0zPNnwMEGIb9TytCrxQ/Resilience-App?node-id=33854%3A19521)

**Screenshot:**
![Screen Shot 2020-06-30 at 1.58.05 PM.png](https://images.zenhubusercontent.com/5ea20d02b3851009106d74e7/d4b358e2-c84c-48ba-81dd-42aaa5cb56ce)

**Comment by jessdwitch** [comment]
Should've done this first, but I was initially unsure how much time I could commit. Can I be assigned to this?

**Comment by DAHuerta** [comment]
Absolutely! I will move it over to in progress. Unfortunately, you have to contribute before I can formally assign you to the ticket. So after this ticket is complete I will be able to formally assign you to a ticket.
