### ISSUE TITLE
Route to "Contribute" tab

### ISSUE THREAD

**Issue by DAHuerta** [factn/resilience-landing-page#52]
Create a route to the "Contribute" tab.

**Comment by jwu910** [comment]
https://elazizi.com/gatsby-js-showcase-contributors-list-for-open-source-project

We should be able to use the all contributors tool to create a json we can parse with gatsby + graphql and then use do w/e we want with the contributors list

**Comment by jwu910** [comment]
So I think we can scope this to the route/page itself, and then we can create issues for the content

**Comment by jwu910** [comment]
@all-contributors please add @DAHuerta for ideas, projectManagement
