### ISSUE TITLE
Update Navigation header

### ISSUE THREAD

**Issue by DAHuerta** [factn/resilience-landing-page#78]
Each page should consist of a navbar at the top of the page.

The navbar should consist of links back to the 'Home' page, 'Partners' page, 'Contribute' page, 'About Us' Page, 'Stories' page, and a 'Get Resilience' link.

[Figma Link](https://www.figma.com/file/GLg0zPNnwMEGIb9TytCrxQ/Resilience-App?node-id=33854%3A19521)

**Mockup**
![Screen Shot 2020-06-05 at 9.49.25 AM.png](https://images.zenhubusercontent.com/5ea20d02b3851009106d74e7/14cf8b1e-9ecd-4779-a666-4ffd79357a3f)

**Comment by jwu910** [comment]
Nav bar needs to be re-organized to match this. We're missing `Home` and `Get the App` needs to be changed to `Get Resilience`

**Comment by chasekaylee** [comment]
@jwu910 do you mind giving me collab rights so I can assign this issue to myself please! Will start working on this now

**Comment by DAHuerta** [comment]
@chasekaylee have you contributed to this project before? Once you contribute I can assign it to you!

**Comment by chasekaylee** [comment]
@DAHuerta Nope first time! Was just curious if I needed perms to assign myself the issue :D

**Comment by DAHuerta** [comment]
We have been trying to limit the hands on the board! However, if you feel like you would work better if you could move them just let Miles know and he can get you permissions.  Just let me know if you want to work on it and I will move it over to in progress, and when your done let me know and I will move it over. Let me know if you have any more questions!

**Comment by chasekaylee** [comment]
@DAHuerta I'm about to get started on the work this afternoon so you can go ahead and throw it in progress 👍. No worries, just trying to get a feel on your guys' workflow

**Comment by DAHuerta** [comment]
@chasekaylee Thank you so much! Welcome to the team!

**Comment by chasekaylee** [comment]
Thanks @DAHuerta excited to help y'all out

**Comment by jwu910** [comment]
@all-contributors please add @chasekaylee for code

**Comment by chasekaylee** [comment]
Sweet. Thanks @jwu910. I'll pick up some more issues when work settles down a bit :D
